# config.yaml

database:
  host: "localhost"
  port: 5432
  user: "admin"
  password: "password123"
  dbname: "appdb_test"
  debug: true
externalconnection:
  authservice:
    host: localhost:50051
appport: :8011
grpcport: :50052
imagepath: "../../public/images" 